services:
  dorfromantik-sakura-scorepad:
    build: .
    image: dorfromantik-sakura-scorepad:latest
    container_name: dorfromantik-sakura-scorepad
    ports:
      - "30028:80"
    restart: unless-stopped
